
<head>
  <meta charset="utf-8" />
  <meta name="description" content="A page with my group details" />
  <meta name="keywords" content="our info" />
  <meta name="author" content="Huynh Ba Thanh"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>About us</title>
  <link rel="stylesheet" href="styles/style.css">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
