
<head>
  <meta charset="utf-8" />
  <meta name="description" content="Project 2" />
  <meta name="keywords" content="project 2" />
  <meta name="author" content="4TL"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Project 2</title>
  <link rel="stylesheet" href="styles/style.css">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
