<header>
<div id="navbar" class="obj-width">
    <a href="index.html"><img class="logo" src="images/4tl-logo.png" alt="4TL Logo"></a>
    <!--responsive navbar-->
    <input type="checkbox" id="nav-toggle" class="nav-toggle">
    <ul id="menu">
        <li><a href="jobs.html">Jobs</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="apply.html">Apply</a></li>
        <li><a href="enhancement.html">Enhancements</a></li>
    </ul>
    <label for="nav-toggle" class="nav-toggle-label">
        <i class='bx bx-menu'></i>
    </label>
</div>
</header>